window.XANH_HOANG_GIA_DATA = {
  "site": {
    "title": "Xanh Hoàng Gia",
    "subtitle": "Website profile thuần HTML, CSS, JS dựng từ nội dung Markdown và toàn bộ visual của PDF gốc."
  },
  "sections": {
    "cover": {
      "label": "Trang Bìa",
      "headline": "Company Profile",
      "description": "Trang mở đầu và thông tin nhận diện của Hoàng Gia Foods."
    },
    "gioi-thieu": {
      "label": "Giới Thiệu",
      "headline": "Lời ngỏ và thông tin doanh nghiệp",
      "description": "Phần mở đầu, lời chào, sứ mệnh ban đầu và dữ liệu doanh nghiệp."
    },
    "su-menh": {
      "label": "Sứ Mệnh",
      "headline": "Tôn chỉ, giá trị cốt lõi, sứ mệnh và tầm nhìn",
      "description": "Các tuyên ngôn cốt lõi định hình cách Hoàng Gia vận hành và phát triển."
    },
    "nang-luc": {
      "label": "Năng Lực",
      "headline": "Cơ cấu vận hành và năng lực đảm bảo chất lượng",
      "description": "Sơ đồ tổ chức, lĩnh vực kinh doanh và định hướng vận hành theo HACCP."
    },
    "quy-trinh": {
      "label": "Quy Trình",
      "headline": "Quy trình nhập hàng và bảo quản",
      "description": "Hệ tiêu chí nhập thực phẩm và nguyên tắc bảo quản tại Hoàng Gia."
    },
    "san-pham": {
      "label": "Sản Phẩm",
      "headline": "Danh mục sản phẩm chính",
      "description": "Các nhóm thực phẩm đang được Hoàng Gia cung ứng."
    },
    "nha-cung-cap": {
      "label": "Nhà Cung Cấp",
      "headline": "Đối tác chiến lược và mạng lưới phân phối",
      "description": "Các nhà cung cấp mục tiêu cùng nội dung đối tác xuất hiện trong profile."
    },
    "chung-nhan": {
      "label": "Chứng Nhận",
      "headline": "Giấy tờ pháp lý và chứng nhận",
      "description": "Các trang chuyển mục và chứng nhận được giữ lại nguyên trạng từ PDF."
    },
    "khach-hang": {
      "label": "Khách Hàng",
      "headline": "Lời kết và danh sách khách hàng",
      "description": "Lời kết của doanh nghiệp cùng hệ khách hàng xuất hiện trong hồ sơ."
    },
    "nha-may": {
      "label": "Nhà Máy",
      "headline": "Nhà máy và kho",
      "description": "Trang kết thúc với chủ đề nhà máy, kho và vận hành hậu cần."
    }
  },
  "pages": [
    {
      "page": 1,
      "title": "Trang bìa company profile",
      "note": "",
      "text": "CÔNG TY TNHH KINH DOANH & SẢN XUẤT\nTHƯƠNG MẠI THỰC PHẨM HOÀNG GIA\nCOMPANY\nPROFILE\nCÔNG TY TNHH KD & SX THƯƠNG MẠI\nTHỰC PHẨM HOÀNG GIA\nĐịa chỉ: TDP Đồng Văn, Phường Đồng Văn, Ninh Bình\nSĐT: 0944 503 111\nEmail: congtyhoanggia8990@gmail.com",
      "image": "assets/pages/page-01.jpg",
      "section": "cover"
    },
    {
      "page": 2,
      "title": "Lời ngỏ và thông tin doanh nghiệp",
      "note": "",
      "text": "Công ty TNHH kinh doanh & sản xuất thương mại thực phẩm Hoàng Gia, xin gửi lời \nchào trân trọng và lời cảm ơn sâu sắc đến Quý Khách hàng và Đối tác đã tin tưởng và đồng hành \ncùng chúng tôi trong suốt chặng đường phát triển.\nĐược thành lập trong bối cảnh tỉnh Hà Nam đang phát triển mạnh mẽ với các khu công nghiệp \nđược đầu tư đồng bộ về cơ sở hạ tầng và các chính sách ưu đãi từ Chính phủ Việt Nam, Công ty \nTNHH Kinh doanh & Sản xuất Thương mại Thực phẩm Hoàng Gia ra đời mang theo sứ mệnh: “Sức \nkhỏe của Người Lao động là sức khỏe của chúng tôi.” Chúng tôi cam kết mang đến những sản phẩm \nthực phẩm chất lượng cao, giá trị dinh dưỡng vượt trội với sự trân trọng và trách nhiệm cao nhất.\nVới triết lý kinh doanh dựa trên đạo đức, sự tận tâm và xem khách hàng là trọng tâm, chúng tôi \ntin rằng chất lượng dịch vụ chính là yếu tố khác biệt. Trải qua 10 năm hoạt động không ngừng học \nhỏi và phát triển, Hoàng Gia đã trở thành thương hiệu uy tín trong lĩnh vực cung cấp thực phẩm \ntại Hà Nam và khu vực miền Bắc. Tầm nhìn của chúng tôi là “Trở thành doanh nghiệp hàng đầu \ntại Việt Nam trong việc chế biến và cung cấp thực phẩm đáp ứng mọi nhu cầu cho tất cả các \nkhách hàng và bếp ăn công nghiệp tại Việt Nam.”\nChúng tôi tự hào sở hữu danh mục sản phẩm đa dạng, phong phú với chất lượng cao và cam kết \nphục vụ khách hàng một cách tốt nhất. Hoàng Gia đã xây dựng một hệ thống cung cấp sản phẩm \nhoàn chỉnh, từ nhập và bảo quản thực phẩm cho đến cung cấp dịch vụ tận tay khách hàng thông \nqua các công ty nấu suất ăn, trường học, nhà hàng, công ty, và các bếp ăn tập thể khác. Chúng tôi \nluôn tuân thủ quy trình nhập và bảo quản thực phẩm đầy đủ và khắt khe để đảm bảo an toàn và \nchất lượng cao nhất.\nXin chân thành cảm ơn Quý Khách hàng và Đối tác đã, đang và sẽ tiếp tục ủng hộ Công ty TNHH \nkinh doanh & sản xuất thương mại thực phẩm Hoàng Gia. Chúng tôi cam kết luôn nỗ lực không \nngừng để mang lại những sản phẩm và dịch vụ tốt nhất, góp phần nâng cao chất lượng cuộc sống \nvà sức khỏe cộng đồng.\nTrân trọng,\nBan Giám Đốc\nHỌ TÊN\nGiám Đốc\nCÔNG TY TNHH KINH DOANH & SẢN XUẤT THƯƠNG MẠI THỰC PHẨM HOÀNG GIA\n2\nTên doanh nghiệp:\nTên tiếng anh:\nMã số thuế:\nĐịa chỉ:\nSố điện thoại:         \nE-Mail:\nCÔNG TY TNHH KINH DOANH & SẢN XUẤT THƯƠNG MẠI THỰC PHẨM HOÀNG GIA\nHOANG GIA FOOD TRADING PRODUCE & BUSINESS COMPANY LIMITED\n0700828342\nTDP Đồng Văn, Phường Đồng Văn, Ninh Bình\n0944 503 111\ncongtyhoanggia8990@gmail.com",
      "image": "assets/pages/page-02.jpg",
      "section": "gioi-thieu"
    },
    {
      "page": 3,
      "title": "Tôn chỉ hoạt động, sứ mệnh và tầm nhìn",
      "note": "",
      "text": "4\n“Cung cấp thực phẩm bằng cái tâm, khách hàng là trọng tâm, chỉ có chất lượng dịch \nvụ mới là khác biệt.”\nTôn chỉ và giá trị cốt lõi luôn đặt khách hàng ở vị trí trung tâm giúp Hoàng Gia xây dựng \nuy tín, tạo dựng mối quan hệ bền vững với khách hàng, và khẳng định vị thế của mình \ntrên thị trường. Bằng cách nhấn mạnh vào chất lượng và sự tận tâm, công ty không chỉ \nđảm bảo sự hài lòng của khách hàng mà còn phát triển bền vững và thành công trong \nngành công nghiệp thực phẩm.\nTÔN CHỈ HOẠT ĐỘNG - GIÁ TRỊ CỐT LÕI\n“Sức khỏe của Người Lao động là sức khỏe của chúng tôi, mang đến cho con \nngười nguồn thực phẩm tốt có giá trị cao về dinh dưỡng và chất lượng bằng \nsự trân trọng sâu sắc và trách nhiệm.”\nSứ mệnh này là kim chỉ nam cho mọi hoạt động của Hoàng Gia, giúp \nđịnh hướng chiến lược, xây dựng thương hiệu và tạo động lực cho nhân \nviên, từ đó khẳng định vị thế của công ty trong ngành thực phẩm.\nSỨ MỆNH\nSỨ MỆNH & TẦM NHÌN\n“Trở thành doanh nghiệp hàng đầu tại Việt Nam trong việc chế biến và \ncung cấp thực phẩm đáp ứng mọi nhu cầu cho tất cả các khách hàng và \nbếp ăn công nghiệp tại Việt Nam.”\nBằng cách tập trung vào chất lượng sản phẩm và dịch vụ, Hoàng Gia \nhướng đến mục tiêu phát triển bền vững và khẳng định vị thế hàng \nđầu trên thị trường thực phẩm Việt Nam.\nTẦM NHÌN\n3",
      "image": "assets/pages/page-03.jpg",
      "section": "su-menh"
    },
    {
      "page": 4,
      "title": "Sơ đồ tổ chức và lĩnh vực kinh doanh",
      "note": "",
      "text": "65\nSƠ ĐỔ TỔ CHỨC LĨNH VỰC KINH DOANH\nĐược thành lập với sứ mệnh mang đến những sản phẩm thực phẩm an toàn, chất lượng và \nđáp ứng nhu cầu ngày càng cao của người tiêu dùng, Hoàng Gia tự hào là một trong những \nđơn vị tiên phong tại Việt Nam sản xuất thực phẩm theo quy trình chuẩn hoá, ứng dụng công \nnghệ cao. \nChúng tôi chuyên cung cấp thực phẩm chất lượng cao với các sản phẩm chủ đạo bao gồm thịt \nlợn, gà, trâu bò và thủy hải sản nhập khẩu. Mỗi sản phẩm này đều được chọn lọc kỹ lưỡng, \nđảm bảo chất lượng cao và an toàn vệ sinh thực phẩm theo các tiêu chuẩn quốc tế. \nKhông chỉ tập trung vào chất lượng mà Hoàng Gia còn đa dạng hóa các dịch vụ để phục vụ mọi \nđối tượng khách hàng. Với khả năng đáp ứng nhu cầu lớn và đa dạng của các khách hàng công \nnghiệp, Hoàng Gia hiện đang là nhà cung cấp thực phẩm cho bếp ăn của nhiều nhà máy, khu \ncông nghiệp, các công trình xây dựng, các trường học và nhiều dự án khác, đảm bảo cung \nứng liên tục và ổn định, đáp ứng các tiêu chuẩn khắt khe về an toàn vệ sinh thực phẩm.\nGIÁM ĐỐC\nPHÓ GIÁM ĐỐC\nTRƯỞNG\nPHÒNG MUA\nHÀNG\nKẾ TOÁN\nTRƯỞNG\nTRƯỞNG\nPHÒNG\nKINH DOANH\nPHÒNG\nQUẢN LÝ\nCHẤT LƯỢNG\nLĨNH VỰC HOẠT ĐỘNG\nTHỰC PHẨM TƯƠI SỐNG\nTHỰC PHẨM ĐÔNG LẠNH\nTHỰC PHẨM ĐÓNG GÓI SẴN",
      "image": "assets/pages/page-04.jpg",
      "section": "nang-luc"
    },
    {
      "page": 5,
      "title": "Trang chuyển mục giấy tờ pháp lý và chứng nhận",
      "note": "Ghi chú: Trang này trong PDF thiên nhiều về trình bày hình ảnh, giấy chứng nhận hoặc tiêu đề chuyển mục. Phần chữ trích xuất được giữ nguyên bên dưới và khi dựng web nên hiển thị thêm PDF gốc hoặc ảnh trang để bám sát thiết kế gốc.\n\n```text\n7 8\nGIẤY TỜ PHÁP LÝ\nGIẤY CHỨNG NHẬN\n&\nGIẤY TỜ PHÁP LÝ\nGIẤY CHỨNG NHẬN\n&\n```\n\n### Trang 6\n\n```text\nTầm nhìn và sự khác biệt, Hoàng Gia đã đáp ứng được việc thị trường thực phẩm ngày càng \nphức tạp, rủi ro tiềm ẩn gây mất VSATTP ngày càng gia tăng, hơn nữa để đáp ứng được nhu \ncầu của 100% đối tượng khách hàng trong và ngoài nước như Nhật Bản, Hàn  Quốc, Trung \nQuốc và Đài Loan. Hoàng Gia Foods tự hào là đơn vị tiên phong và đầu tiên tại Việt Nam được \ncấp chứng nhận Quốc tế HACCP – ( Hazard Analysis and Critical Control Points – hệ thống \nphân tích mối nguy và kiểm soát điểm tới hạn”, hay hệ thống phân tích, xác định và tổ chức \nkiểm soát các mối nguy trọng yếu trong quá trình sản xuất và chế biến thực phẩm; và là hệ \nthống quản lý chất lượng dựa trên cơ sở phân tích các mối nguy và các điểm kiểm soát trọng \nyếu. Đó là công cụ phân tích nhằm đảm bảo an toàn vệ sinh và chất lượng thực phẩm. HACCP \nbao gồm những đánh giá có hệ thống đối với tất cả các bước có liên quan trong quy trình chế \nbiến thực phẩm, đồng thời xác định những bước trọng yếu với an toàn chất lượng thực phẩm. \nCông cụ này cho phép tập trung nguồn lực kỹ thuật, chuyên môn vào những bước chế biến có \nảnh hưởng quyết định đến an toàn chất lượng thực phẩm. HACCP là một bộ tiêu chuẩn quốc \ntế về phân tích mối nguy và điểm kiểm soát tới hạn, tiêu chuẩn HACCP nằm trong hệ thống \ntiêu chuẩn CODEX – cơ sở dữ liệu về an toàn thực phẩm do tổ chức lương thực và Nông nghiệp \nthế giới FAO và tổ chức y tế thế giới WHO xây dựng.\nTiêu chuẩn HACCP Codex 2020 đưa ra các nguyên tắc chung để sản xuất thực phẩm an toàn \nvà phù hợp cho nhu cầu tiêu dùng dựa trên các biện pháp kiểm soát vệ sinh và an toàn thực \nphẩm cần thiết được thực hiện trong sản xuất ( bao gồm cả sản xuất ban đầu), chế biến, chuẩn \nbị, bao gói, bảo quản, phân phối, bán lẻ, kinh doanh dịch vụ ăn uống, vận chuyển thực phẩm \ncũng như các biện pháp kiểm soát an toàn thực phẩm cụ thể sẽ được áp dụng ở các bước nhất \nđịnh trong toàn bộ chuỗi thực phẩm khi thích hợp. \nTrong lĩnh vực hoạt động của mình Hoàng Gia luôn chú trọng chất lượng, việc đảm bảo vệ sinh \nATTP là cốt lõi, luôn đặt sức khỏe người lao động, của khách hàng là trọng tâm, chính vì vậy HACCP \nlà lựa chọn hàng đầu để Hoàng Gia thực hiện sứ mệnh của mình. Trong tương lai, HACCP sẽ là \ntiền đề để Hoàng Gia thực hiện các mục tiêu quan trọng khác trên chặng đường phát triển trở \nthành một Doanh nghiệp hàng đầu Việt Nam trong lĩnh vực kinh doanh thực phẩm và bán lẻ \nthực phẩm.\n109\nGIẤY TỜ PHÁP LÝ\nGIẤY CHỨNG NHẬN\n&\n```\n\n### Trang 7\n\n```text\nQUY TRÌNH NHẬP\nTHỰC PHẨM TẠI HOÀNG GIA\nTIÊU CHÍ NHẬP HÀNG\nTẠI CÔNG TY HOÀNG GIA\n1211\nB01.\nB02.\nB03.\nB04.\nB05.\nPhân công người chuyên trách nhập thực phẩm. Người nhập thực \nphẩm là người chuyên trách do Doanh nghiệp chỉ định, được đào tạo, \ntập huấn và có kiến thức cơ bản về thực phẩm cũng như vệ sinh an \ntoàn thực phẩm.\nNhà cung ứng thứ cấp, nhà sản xuất phải xuất trình đầy đủ hóa đơn, \nchứng từ, nguồn gốc, xuất xứ của hàng hóa. Sau khi nhập hàng phải \nvào sổ sách đầy đủ và có ký xác nhận của hai bên.\nKiểm tra chất lượng hàng hóa. Chỉ nhập hàng đủ tiêu chuẩn, kiên \nquyết trả về hàng hóa không đảm bảo chất lượng, ôi thiu, dịch bệnh \nhoặc quá hạn sử dụng.\nNhập hàng. Hàng được nhập sau sau khi được kiểm tra kỹ về mặt giấy \ntờ đảm bảo đầy đủ hồ sơ theo quy định đối với từng loại mặt hàng và \nđảm bảo các tiêu chí nhập  hàng đối với từng loại hàng hóa riêng biệt \ntheo tiêu chuẩn của Hoàng Gia.\nBảo quản thực phẩm trong kho. Thực phẩm sau khi được nhập phải \ntiến hành sơ chế, rửa sạch và bảo quản theo quy trình. Kho bảo quản \nphải khô ráo, ngăn nắp, sạch sẽ, thoáng mát và có các ngăn riêng biệt \ncho từng loại thực phẩm.\nTiêu Chí Nhập Hàng: Thịt tươi, màng ngoài khô, không bị nhớt, mùi và màu sắc bình \nthường, khối thịt rắn chắc, có độ đàn hồi cao. Phần mỡ màu trong hoặc màu đặc trưng \ncủa từng loại thịt, bì không có lấm chấm xuất huyết màu đỏ tím, tủy xương trong, không \ncó mùi ôi. Phần thịt nạc không có ấu trùng sán màu trắng nhỏ bằng hạt gạo….\nLOẠI HÀNG: Thịt tươi\nTiêu Chí Nhập Hàng: Cá đang sống hoặc đã chết nhưng phải tươi: thân cá co cứng, mắt \ncá trong suốt, giác mạc đàn hồi, miệng ngậm cứng, mang màu đỏ tươi, vẩy tươi óng ánh \ndính chặt vào thân, thịt rắn chắc, có đàn hồi và dính chặt vào xương.\nCác loại thủy hải sản khác: Tươi, màu sắc bình thường đặc trưng của từng loại, không có \nmùi ươn….\nLOẠI HÀNG: Cá và các loại thủy hải sản\nTiêu Chí Nhập Hàng: Vỏ trứng màu sáng, không có vệt xám đen, không bị dập và có \nmàu hồng trong suốt khi soi qua ánh sáng và có giấy kiểm dịch của cơ quan vệ sinh dịch \ntễ địa phương ( nếu có).\nLOẠI HÀNG: Trứng\nTiêu Chí Nhập Hàng: Chọn các loại rau quả tươi, không bị dập nát, héo, úa, bị sâu bệnh. \nKhông nhập các loại rau quả có màu sắc khác thường hay có mùi lạ khác thường hoặc \nmùi thuốc sâu. Nếu có vấn đề phải báo cáo ngay cho quản lý hoặc người có trách nhiệm \ngiải quyết  hoặc trả lại nhà cung cấp.\nLOẠI HÀNG: Rau, củ, quả, nông sản…\nTiêu Chí Nhập Hàng: Thực phẩm đóng hộp, đóng gói phải ghi đầy đủ nhãn, mác, tên \nsản phẩm, trọng lượng, thành phần, cách bảo quản và sử dụng, nơi sản xuất chế \nbiến.Thực phẩm đóng hộp, đóng gói phải do nhà sản xuất được phép của cơ quan y tế, \nđược đăng ký chất lượng và ghi rõ thời hạn sử dụng.\nLOẠI HÀNG: Thực phẩm khô và hàng nhập khẩu đóng gói\n```\n\n### Trang 8\n\n```text\n10\nQUY TRÌNH BẢO QUẢN\nTHỰC PHẨM TẠI HOÀNG GIA\nTất cả thực phẩm khô phải được bảo quản trong bao bì hoặc đóng \ngói cẩn thận và có tem dán nhãn ghi chú ngày đóng gói và thời hạn \nsử dụng. Kho chứa thực phẩm khô phải thoáng mát, sạch sẽ, có kệ, \npallet xếp hàng cách mặt đất và mặt tường tối thiểu 25cm. Hàng hóa \nđược đảm bảo xếp phân khu từng mặt hàng, chủng loại hàng hóa.\nĐỐI VỚI THỰC PHẨM KHÔ ĐÓNG GÓI\nKhi vận chuyển phải được giữ lạnh ở nhiệt độ cần thiết và được lưu \nvào kho đông lạnh. Hàng hóa thực phẩm trước khi cho vào bảo quản \nphải được phân loại, đóng gói hoặc dùng dung cụ chuyên biệt để \nchứa đựng đảm bảo việc các loại thực phẩm được ngăn cách đúng \nquy định và đảm bảo vệ sinh ATTP .\nĐỐI VỚI SẢN PHẨM THỊT, CÁ, GÀ...\nCác loại rau củ quả phải được sơ chế làm sạch dị vật, bùn đất và các \ncọng rau úa hỏng và để nơi khô ráo, thoáng mát. Rau củ quả được \nxếp ngay ngắn vào dụng cụ chuyên dụng như: sọt, công thoáng để \nđảm bảo thực phẩm không bị ứ nước, đảm bảo khô thoáng trong \nsuốt quá trình bảo quản.\nĐỐI VỚI THỰC PHẨM RAU CỦ QUẢ\nHàng hóa bắt buộc phải được bảo quản trong kho đông \ncó nhiệt độ bảo quản là -20 °C đối với các loại cá, là -18°C \nđối với các loại thịt.\nĐỐI VỚI THỰC PHẨM LÀ HÀNG HÓA ĐÔNG LẠNH NHẬP KHẨU NHƯ\nTHỊT, CÁ, GÀ ĐÔNG LẠNH NHẬP KHẨU\n13\nCÁC SẢN PHẨM CHÍNH\nHOÀNG GIA FOODS\n```\n\n### Trang 9\n\n```text\n1615\nRau củ quả tươi Thịt gia súc\nGia cầm tươi\n Thủy, hải sản tươi sống\nGạo\n Bánh tráng miệng\nCÁC SẢN PHẨM CHÍNH\nHOÀNG GIA FOODS\nCác loại sữa\n Ngũ cốc\nThực phẩm bao gói sẵn Thịt gia súc, gia cầm đông lạnh\nThủy hải sản đông lạnh nhập khẩu\nCÁC SẢN PHẨM CHÍNH\nHOÀNG GIA FOODS\n```\n\n### Trang 10\n\n```text\n18\nCÁC NHÀ CUNG CẤP MỤC TIÊU\nHTX Nông sản Sạch Bảo An là một trong những \nđối tác chiến lược và uy tín của Công ty TNHH \nKinh Doanh & Sản Xuất Thương Mại Thực \nPhẩm Hoàng Gia. Với cam kết cung cấp các sản \nphẩm nông sản sạch, chất lượng cao, Bảo An \nđã và đang góp phần quan trọng vào việc đảm \nbảo nguồn nguyên liệu đầu vào an toàn và \ngiàu dinh dưỡng cho các sản phẩm thực phẩm \ncủa Hoàng Gia.\nHTX Nông Sản Sạch Bảo An luôn đặt chất lượng \nlên hàng đầu. Các sản phẩm nông sản được canh \ntác bằng phương pháp hữu cơ, không sử dụng \nhóa chất độc hại, đảm bảo an toàn cho sức khỏe \nngười tiêu dùng, đạt chứng nhận VIETGAP . Quá \ntrình sản xuất từ gieo trồng, chăm sóc đến thu \nhoạch đều tuân thủ các quy trình kiểm soát chất \nlượng nghiêm ngặt, giúp giữ nguyên giá trị dinh \ndưỡng và hương vị tự nhiên của sản phẩm.\nNông trại của HTX Bảo An áp dụng các \nphương pháp canh tác bền vững, bảo vệ môi \ntrường và phát triển nông nghiệp xanh. Họ \nsử dụng phân bón hữu cơ, biện pháp sinh \nhọc và kỹ thuật tưới tiêu tiên tiến, giúp giảm \nthiểu tác động tiêu cực đến môi trường và \nduy trì độ phì nhiêu của đất. Điều này không \nchỉ đảm bảo chất lượng sản phẩm mà còn \ngóp phần bảo vệ môi trường sống.\nHTX NÔNG SẢN\nSẠCH BẢO AN\n01.\n17\nĐể đảm bảo chất lượng và an toàn của các sản phẩm thực phẩm, Công ty TNHH Kinh Doanh & Sản \nXuất Thương Mại Thực Phẩm Hoàng Gia hợp tác chặt chẽ với những nhà cung cấp đầu vào uy tín và \nđáng tin cậy. Những đối tác này cung cấp nguyên liệu chất lượng cao, đáp ứng các tiêu chuẩn nghiêm \nngặt về an toàn thực phẩm và đóng góp vào sự phát triển bền vững của công ty.\nCÁC NHÀ CUNG CẤP\nMỤC TIÊU\n```\n\n### Trang 11\n\nGhi chú: Trang này trong PDF thiên nhiều về trình bày hình ảnh, giấy chứng nhận hoặc tiêu đề chuyển mục. Phần chữ trích xuất được giữ nguyên bên dưới và khi dựng web nên hiển thị thêm PDF gốc hoặc ảnh trang để bám sát thiết kế gốc.\n\n```text\n2019\nGIẤY CHỨNG NHẬN\nHỢP TÁC XÃ NÔNG SẢN SẠCH BẢO AN\n```\n\n### Trang 12\n\n```text\n22\nVới hệ thống trang trại gà công nghệ cao theo tiêu \nchuẩn Châu Âu với quy trình chăn nuôi khép kín, trước \nkhi cung cấp tới Hoàng Gia, gà thịt được nuôi dưỡng \ntrong môi trường an toàn, bằng nguồn thức ăn thảo \ndược, hoàn toàn không kháng sinh. \nNông sản Phú Gia là tập đoàn tiên phong tại Việt Nam ứng \ndụng công nghệ mới tại Việt Nam. Với triết lý kinh doanh \nlấy sự “An toàn” là bước đi vững chắc và lâu dài, Nông sản \nPhú Gia tiên phong sản xuất theo mô hình chuỗi giá trị \n“Thức ăn - Chăn nuôi - Thực phẩm - Phân bón - Cây trồng”.\nVới nền chăn nuôi nông nghiệp hiện đại và bền vững, \nđảm bảo cung cấp thực phẩm an toàn cho người tiêu \ndùng, Nông Sản Phú Gia là một trong những đối tác \nchiến lược và đáng tin cậy của Công ty TNHH Kinh \nDoanh & Sản Xuất Thương Mại Thực Phẩm Hoàng Gia \ntrong việc cung cấp thịt gà chất lượng cao.\nToàn bộ quy trình sản xuất của Phú Gia Food từ chăn \nnuôi, giết mổ, chế biến đến đóng gói đều được thực hiện \ntheo các tiêu chuẩn quốc tế về an toàn vệ sinh thực \nphẩm. Công ty áp dụng công nghệ hiện đại và hệ thống \nquản lý chất lượng nghiêm ngặt, đảm bảo mỗi sản phẩm \nđều đạt chuẩn về vệ sinh và an toàn thực phẩm trước khi \nđến tay người tiêu dùng.\nCÁC NHÀ CUNG CẤP\nMỤC TIÊU\nCÔNG TY CP NÔNG SẢN PHÚ GIA02.\n21\nCÁC NHÀ CUNG CẤP MỤC TIÊU\n```\n\n### Trang 13\n\nGhi chú: Trang này trong PDF thiên nhiều về trình bày hình ảnh, giấy chứng nhận hoặc tiêu đề chuyển mục. Phần chữ trích xuất được giữ nguyên bên dưới và khi dựng web nên hiển thị thêm PDF gốc hoặc ảnh trang để bám sát thiết kế gốc.\n\n```text\n2423\nGIẤY CHỨNG NHẬN\nCÔNG TY CP NÔNG SẢN PHÚ GIA\n```\n\n### Trang 14\n\n```text\n26\nVinh Anh Food tự hào là người đi đầu xây dựng chuỗi liên kết sản xuất thịt heo sạch an toàn, truy \nxuất nguồn gốc, tạo ra sản phẩm chất lượng cao. Nhà máy giết mổ của Vinh Anh Food là một \ntrong những nhà máy công nghệ đồng bộ, hiện đại bậc nhất miền Bắc. Khác với các lò giết mổ \nthủ công, quy trình của Công ty được thực hiện một cách khoa học, bài bản, đảm bảo an toàn \nthực phẩm và phúc lợi động vật. Quy trình sản xuất – chế biến của nhà máy được đảm bảo vận \nhành nghiêm ngặt theo tiêu chuẩn ISO 22000. 100% thực phẩm được phân phối đến Hoàng Gia \nbằng ô tô chuyên dùng có hệ thống lạnh đảm bảo tươi ngon, hợp vệ sinh.\nCÁC NHÀ CUNG CẤP\nMỤC TIÊU\nVINH ANH FOOD\n03.\nVinh Anh Food là một trong những đối tác \nchiến lược và quan trọng của Công ty TNHH \nKinh Doanh & Sản Xuất Thương Mại Thực \nPhẩm Hoàng Gia, chuyên cung cấp thịt lợn \nchất lượng cao. Với nhiều năm kinh nghiệm \ntrong lĩnh vực chăn nuôi và cung ứng thực \nphẩm, Vinh Anh Food luôn đảm bảo mang \nđến những sản phẩm thịt lợn tươi ngon, an \ntoàn và giàu dinh dưỡng, đáp ứng các tiêu \nchuẩn khắt khe về vệ sinh an toàn thực phẩm.\n25\nCÁC NHÀ CUNG CẤP\nMỤC TIÊU\n```\n\n### Trang 15\n\nGhi chú: Trang này trong PDF thiên nhiều về trình bày hình ảnh, giấy chứng nhận hoặc tiêu đề chuyển mục. Phần chữ trích xuất được giữ nguyên bên dưới và khi dựng web nên hiển thị thêm PDF gốc hoặc ảnh trang để bám sát thiết kế gốc.\n\n```text\n2827\nCÔNG TY CP CÔNG NGHỆ THỰC PHẨM VINH ANH\n```\n\n### Trang 16\n\nGhi chú: Trang này trong PDF thiên nhiều về trình bày hình ảnh, giấy chứng nhận hoặc tiêu đề chuyển mục. Phần chữ trích xuất được giữ nguyên bên dưới và khi dựng web nên hiển thị thêm PDF gốc hoặc ảnh trang để bám sát thiết kế gốc.\n\n```text\n30\nCÁC NHÀ CUNG CẤP\nMỤC TIÊU\nCÁC NHÀ PHÂN PHỐI KHÁC\n04.\nCÁC NHÀ CUNG CẤP\nMỤC TIÊU\n29\n```\n\n### Trang 17\n\n```text\n31\nKHÁCH HÀNG\nLỜI KẾT\nChúng tôi, Công ty TNHH Kinh doanh & Sản xuất Thương mại Thực phẩm Hoàng Gia, xin gửi lời \ncảm ơn chân thành đến quý khách hàng, đối tác và toàn thể nhân viên đã luôn đồng hành và ủng \nhộ chúng tôi trong suốt chặng đường phát triển. Sự tin tưởng và hỗ trợ từ quý vị chính là động \nlực để chúng tôi không ngừng nỗ lực cải tiến và hoàn thiện từng ngày.\nHoàng Gia cam kết tiếp tục mang đến những sản phẩm thực phẩm chất lượng cao, an toàn và \ngiàu dinh dưỡng, đáp ứng mọi nhu cầu của khách hàng. Chúng tôi tin tưởng rằng, với sự đoàn \nkết và nỗ lực của toàn bộ đội ngũ, cùng với sự ủng hộ từ quý khách hàng và đối tác, Hoàng Gia \nsẽ ngày càng phát triển mạnh mẽ, vững chắc trên thị trường, góp phần nâng cao chất lượng cuộc \nsống và sức khỏe cho cộng đồng.\nChúng tôi rất mong tiếp tục nhận được sự tin tưởng và hợp tác từ quý vị trong tương lai. Xin trân \ntrọng cảm ơn và chúc quý khách hàng, đối tác sức khỏe, thành công và hạnh phúc.\nTrân trọng,\nCông ty TNHH Kinh doanh & Sản xuất Thương mại Thực phẩm Hoàng Gia\n24\nCÔNG TY TNHH DỊCH VỤ THƯƠNG MẠI HC TOÀN CẦU\n76 đường Thụy Phương, P. Đông Ngạc, Q. Bắc Từ \nLiêm, TP Hà Nội\nCÔNG TY TNHH SẢN XUẤT THƯƠNG MẠI\nDỊCH VỤ NHẬT CƯỜNG\nQL 38, P. Yên Bắc, Thị xã Duy Tiên, tỉnh Hà Nam, \nViệt Nam\nCÔNG TY TNHH DỊCH VỤ ẨM THỰC\nSEONG - HO\nKhu Công Nghiệp Đồng Văn I, P. Bạch \nThượng, Thị xã Duy Tiên, Tỉnh Hà \nNam, Việt Nam\nCÔNG TY TNHH SUẤT ĂN ALOCOM\nKhu hành chính 3, P. Liên Bảo, TP. \nVĩnh Yên, Tỉnh Vĩnh Phúc, Việt Nam\nCÔNG TY TNHH HỆ THỐNG\nDÂY DẪN ECO\nKCN Đồng Văn IV, Xã Đại Cương, \nHuyện Kim Bảng, Hà Nam\nCÔNG TY TNHH DỊCH VỤ ĂN UỐNG\nÁNH DƯƠNG FOOD\n45/57/20 Nguyễn Văn Đậu, P. 6, Q. \nBình Thạnh, TP Hồ Chí Minh, Việt Nam\nCÔNG TY TNHH MEATDELI HN\nLô CN-02, Khu công nghiệp Đồng \nVăn IV, xã Đại Cương, huyện Kim \nBảng, tỉnh Hà Nam, Việt Nam\nCÔNG TY TNHH PHÁT TRIỂN\nBÌNH THUẬN\nLô CN 3, KCN Đồng Văn IV, xã Đại \nCương, huyện Kim Bảng, Hà Nam\nCÔNG TY TNHH DỊCH VỤ FNC\nSố 10 Nguyễn Quý Tân, P. Liên Bảo \nThành, phố Vĩnh Yên, tỉnh Vĩnh Phúc, \nViệt Nam\nCÔNG TY TNHH SUNFOODS\nCATERING\nThôn 2 Hoàng Lâu, Xã Hồng Phong, \nHuyện An Dương, Hải Phòng\nCÔNG TY TNHH TÂN NÉT VIỆT\nTDP Đông Hải, phường Duy Hải, thị xã Duy Tiên, tỉnh Hà \nNam\nCÔNG TY TNHH THỰC PHẨM PHÚC LƯƠNG\nLÔ 30A3 khu nhà ở Xi măng Bút Sơn, P. Châu Sơn, \nTP. Phủ Lý, Hà Nam\nCÔNG TY TNHH DỊCH VỤ VICA\nTầng 11, Tòa nhà Việt Á, số 9 Duy \nTân, P. Dịch Vọng Hậu, Q. Cầu \nGiấy, TP.Hà Nội, Việt Nam\nCÔNG TY TNHH THÀNH CÔNG HPT\nLô 15, 16, 17 - N06 đường Thanh Niên, \nkhu dân cư phía Nam, P. Dĩnh Kế, TP. \nBắc Giang, Tỉnh Bắc Giang, Việt Nam\nCÔNG TY TNHH JUNGWON\nELECTRONICS VIETNAM\nLô CN10.1, đường D6, Khu công \nnghiệp Châu Sơn, P. Châu Sơn, TP. \nPhủ Lý, Tỉnh Hà Nam, Việt Nam\nCÔNG TY CP QUỐC TẾ TÂN Á HÀ NAM\nKhu công nghiệp Thanh Liêm, Thị \ntrấn Kiện Khê, Huyện Thanh Liêm, \nTỉnh Hà Nam, Việt Nam\nCÔNG TY TNHH THỰC PHẨM 3S HÀ NAM\nTổ dân phố Đồng Văn, Phường Đồng Văn, Thị Xã \nDuy Tiên, Hà Nam\nCÔNG TY TNHH DỊCH VỤ THƯƠNG MẠI TC FOODS\nLô CN05, Khu Công nghiệp hỗ trợ Đồng Văn III, \nPhường Hoàng Đông, Thị Xã Duy Tiên, Hà Nam\nCÔNG TY TNHH THỰC PHẨM HG HÀ NAM\nNguyễn Hữu Tiến, Phường Đồng Văn, Thị Xã \nDuy Tiên, Hà Nam\nCÔNG TY TNHH F&C SERVICE\nLầu 3, Toà nhà B15, Số 79/8 đường Hoàng Văn \nThái, Khu TTTM Tài Chính Quốc Tế Phú Mỹ \nHưng, P.Tân Phú, Q.7, TP Hồ Chí Minh\nCHI NHÁNH CÔNG TY TNHH DỊCH VỤ DI VINA\nL3-08-09 Tầng 3 Vincom Plaza Skylake Phạm Hùng, \nô đất E1.3,, P. Mỹ Đình 1, Q. Nam Từ Liêm, Hà Nội\nCÔNG TY TNHH OLIVE\nSố 49, đường số 23 (TP. Giao Lưu), P. Cổ \nNhuế 2, Q. Bắc Từ Liêm, TP. Hà Nội, Việt \nNam\n```\n\n### Trang 18\n\nGhi chú: Trang này trong PDF thiên nhiều về trình bày hình ảnh, giấy chứng nhận hoặc tiêu đề chuyển mục. Phần chữ trích xuất được giữ nguyên bên dưới và khi dựng web nên hiển thị thêm PDF gốc hoặc ảnh trang để bám sát thiết kế gốc.",
      "text": "NHÀ MÁY - KHO\nNHÀ MÁY - KHO\n3433",
      "image": "assets/pages/page-05.jpg",
      "section": "chung-nhan"
    }
  ],
  "pageImages": [
    "assets/pages/page-01.jpg",
    "assets/pages/page-02.jpg",
    "assets/pages/page-03.jpg",
    "assets/pages/page-04.jpg",
    "assets/pages/page-05.jpg",
    "assets/pages/page-06.jpg",
    "assets/pages/page-07.jpg",
    "assets/pages/page-08.jpg",
    "assets/pages/page-09.jpg",
    "assets/pages/page-10.jpg",
    "assets/pages/page-11.jpg",
    "assets/pages/page-12.jpg",
    "assets/pages/page-13.jpg",
    "assets/pages/page-14.jpg",
    "assets/pages/page-15.jpg",
    "assets/pages/page-16.jpg",
    "assets/pages/page-17.jpg",
    "assets/pages/page-18.jpg"
  ],
  "extractedImages": [
    "assets/extracted/img-001-xref-2212.jpeg",
    "assets/extracted/img-002-xref-2163.jpeg",
    "assets/extracted/img-003-xref-2214.jpeg",
    "assets/extracted/img-004-xref-2216.jpeg",
    "assets/extracted/img-005-xref-2218.jpeg",
    "assets/extracted/img-006-xref-2166.jpeg",
    "assets/extracted/img-007-xref-2220.jpeg",
    "assets/extracted/img-008-xref-2165.jpeg",
    "assets/extracted/img-009-xref-2164.jpeg",
    "assets/extracted/img-010-xref-10.jpeg",
    "assets/extracted/img-011-xref-12.jpeg",
    "assets/extracted/img-012-xref-80.jpeg",
    "assets/extracted/img-013-xref-81.jpeg",
    "assets/extracted/img-014-xref-83.jpeg",
    "assets/extracted/img-015-xref-85.png",
    "assets/extracted/img-016-xref-87.jpeg",
    "assets/extracted/img-017-xref-89.jpeg",
    "assets/extracted/img-018-xref-90.jpeg",
    "assets/extracted/img-019-xref-92.jpeg",
    "assets/extracted/img-020-xref-94.jpeg",
    "assets/extracted/img-021-xref-96.jpeg",
    "assets/extracted/img-022-xref-98.jpeg",
    "assets/extracted/img-023-xref-100.jpeg",
    "assets/extracted/img-024-xref-102.jpeg",
    "assets/extracted/img-025-xref-104.png",
    "assets/extracted/img-026-xref-161.jpeg",
    "assets/extracted/img-027-xref-163.jpeg",
    "assets/extracted/img-028-xref-165.jpeg",
    "assets/extracted/img-029-xref-167.jpeg",
    "assets/extracted/img-030-xref-136.png",
    "assets/extracted/img-031-xref-148.png",
    "assets/extracted/img-032-xref-158.png",
    "assets/extracted/img-033-xref-185.jpeg",
    "assets/extracted/img-034-xref-187.jpeg",
    "assets/extracted/img-035-xref-189.jpeg",
    "assets/extracted/img-036-xref-191.jpeg",
    "assets/extracted/img-037-xref-488.png",
    "assets/extracted/img-038-xref-490.png",
    "assets/extracted/img-039-xref-491.png",
    "assets/extracted/img-040-xref-493.png",
    "assets/extracted/img-041-xref-494.png",
    "assets/extracted/img-042-xref-496.png",
    "assets/extracted/img-043-xref-1650.jpeg",
    "assets/extracted/img-044-xref-1651.jpeg",
    "assets/extracted/img-045-xref-1653.jpeg",
    "assets/extracted/img-046-xref-1655.jpeg",
    "assets/extracted/img-047-xref-1657.jpeg",
    "assets/extracted/img-048-xref-1682.jpeg",
    "assets/extracted/img-049-xref-1684.jpeg",
    "assets/extracted/img-050-xref-1686.jpeg",
    "assets/extracted/img-051-xref-1688.jpeg",
    "assets/extracted/img-052-xref-1690.jpeg",
    "assets/extracted/img-053-xref-1692.jpeg",
    "assets/extracted/img-054-xref-1694.jpeg",
    "assets/extracted/img-055-xref-1696.jpeg",
    "assets/extracted/img-056-xref-1707.jpeg",
    "assets/extracted/img-057-xref-1708.jpeg",
    "assets/extracted/img-058-xref-1709.jpeg",
    "assets/extracted/img-059-xref-1710.jpeg",
    "assets/extracted/img-060-xref-1711.jpeg",
    "assets/extracted/img-061-xref-1712.jpeg",
    "assets/extracted/img-062-xref-1713.jpeg",
    "assets/extracted/img-063-xref-1714.jpeg",
    "assets/extracted/img-064-xref-1715.jpeg",
    "assets/extracted/img-065-xref-1716.jpeg",
    "assets/extracted/img-066-xref-1717.jpeg",
    "assets/extracted/img-067-xref-1718.jpeg",
    "assets/extracted/img-068-xref-1719.jpeg",
    "assets/extracted/img-069-xref-1720.jpeg",
    "assets/extracted/img-070-xref-1721.jpeg",
    "assets/extracted/img-071-xref-1722.jpeg",
    "assets/extracted/img-072-xref-1723.jpeg",
    "assets/extracted/img-073-xref-1724.jpeg",
    "assets/extracted/img-074-xref-1725.jpeg",
    "assets/extracted/img-075-xref-1726.jpeg",
    "assets/extracted/img-076-xref-1727.jpeg",
    "assets/extracted/img-077-xref-1728.jpeg",
    "assets/extracted/img-078-xref-1740.jpeg",
    "assets/extracted/img-079-xref-1742.jpeg",
    "assets/extracted/img-080-xref-1744.jpeg",
    "assets/extracted/img-081-xref-1745.jpeg",
    "assets/extracted/img-082-xref-1747.jpeg",
    "assets/extracted/img-083-xref-1749.jpeg",
    "assets/extracted/img-084-xref-1751.jpeg",
    "assets/extracted/img-085-xref-1759.jpeg",
    "assets/extracted/img-086-xref-1761.jpeg",
    "assets/extracted/img-087-xref-1763.jpeg",
    "assets/extracted/img-088-xref-1765.jpeg",
    "assets/extracted/img-089-xref-1766.jpeg",
    "assets/extracted/img-090-xref-1767.jpeg",
    "assets/extracted/img-091-xref-1769.jpeg",
    "assets/extracted/img-092-xref-1770.jpeg",
    "assets/extracted/img-093-xref-1771.jpeg",
    "assets/extracted/img-094-xref-1772.jpeg",
    "assets/extracted/img-095-xref-1774.jpeg",
    "assets/extracted/img-096-xref-1854.jpeg",
    "assets/extracted/img-097-xref-1855.jpeg",
    "assets/extracted/img-098-xref-1857.jpeg",
    "assets/extracted/img-099-xref-1859.jpeg",
    "assets/extracted/img-100-xref-1861.jpeg",
    "assets/extracted/img-101-xref-1862.jpeg",
    "assets/extracted/img-102-xref-1863.jpeg",
    "assets/extracted/img-103-xref-1880.jpeg",
    "assets/extracted/img-104-xref-1882.jpeg",
    "assets/extracted/img-105-xref-1883.jpeg",
    "assets/extracted/img-106-xref-1885.jpeg",
    "assets/extracted/img-107-xref-1886.jpeg",
    "assets/extracted/img-108-xref-1887.jpeg",
    "assets/extracted/img-109-xref-1888.jpeg",
    "assets/extracted/img-110-xref-1889.jpeg",
    "assets/extracted/img-111-xref-1890.jpeg",
    "assets/extracted/img-112-xref-1891.jpeg",
    "assets/extracted/img-113-xref-1892.jpeg",
    "assets/extracted/img-114-xref-1926.jpeg",
    "assets/extracted/img-115-xref-1927.jpeg",
    "assets/extracted/img-116-xref-1928.jpeg",
    "assets/extracted/img-117-xref-1929.jpeg",
    "assets/extracted/img-118-xref-1930.jpeg",
    "assets/extracted/img-119-xref-1937.jpeg",
    "assets/extracted/img-120-xref-1938.jpeg",
    "assets/extracted/img-121-xref-1939.jpeg",
    "assets/extracted/img-122-xref-1940.jpeg",
    "assets/extracted/img-123-xref-1941.jpeg",
    "assets/extracted/img-124-xref-1942.jpeg",
    "assets/extracted/img-125-xref-1943.jpeg",
    "assets/extracted/img-126-xref-1971.jpeg",
    "assets/extracted/img-127-xref-1972.jpeg",
    "assets/extracted/img-128-xref-1973.jpeg",
    "assets/extracted/img-129-xref-1975.jpeg",
    "assets/extracted/img-130-xref-1997.jpeg",
    "assets/extracted/img-131-xref-1998.jpeg",
    "assets/extracted/img-132-xref-1999.jpeg",
    "assets/extracted/img-133-xref-2001.png",
    "assets/extracted/img-134-xref-2002.jpeg",
    "assets/extracted/img-135-xref-2003.jpeg",
    "assets/extracted/img-136-xref-2004.png",
    "assets/extracted/img-137-xref-2005.png",
    "assets/extracted/img-138-xref-2006.jpeg",
    "assets/extracted/img-139-xref-2007.jpeg",
    "assets/extracted/img-140-xref-2009.png",
    "assets/extracted/img-141-xref-2010.jpeg",
    "assets/extracted/img-142-xref-2012.png",
    "assets/extracted/img-143-xref-2014.jpeg",
    "assets/extracted/img-144-xref-2020.jpeg",
    "assets/extracted/img-145-xref-2022.jpeg",
    "assets/extracted/img-146-xref-2024.jpeg",
    "assets/extracted/img-147-xref-2026.jpeg",
    "assets/extracted/img-148-xref-2028.jpeg",
    "assets/extracted/img-149-xref-2030.jpeg",
    "assets/extracted/img-150-xref-2032.jpeg",
    "assets/extracted/img-151-xref-2034.jpeg",
    "assets/extracted/img-152-xref-2036.jpeg",
    "assets/extracted/img-153-xref-2038.jpeg",
    "assets/extracted/img-154-xref-2040.jpeg"
  ]
};
